### ISSUE TITLE
Corrupted/incorrect output file

### ISSUE THREAD

**Issue by sklprogs** [mps-youtube/pafy#217] opened 2018-08-21 16:27 UTC
Hello! When I'm trying to download a specific URL (see below),  I get an output file that is identified as "ISO Media, MPEG v4 system, version 2", however, it's size is just 220K. I tried to do it several times, used preftype = 'mp4', ftypestrict = True, but I get the same output.
```
>>> import pafy
>>> video = pafy.new('YDCczit4MuQ')
>>> stream = video.getbest()
>>> stream.download()
```
Thanks again for your great work.

**Comment by ritiek** [comment] 2018-08-22 04:35
I was able to reproduce this problem with your code the moment you reported this issue.

However, I just tried your code again and it seems to be downloading fine for me now. Dunno if this was an issue with YouTube itself but can you test it out again and see if it works for you now as well?

**Comment by sklprogs** [comment] 2018-08-22 06:07
@ritiek 
Yes, you are right. It works for me now. This is probably one of the Youtube-specific problems. The other one that I have encountered was "urllib.error.HTTPError: HTTP Error 403: Forbidden" when trying to download after a certain time-out (just do pafy.new(any_URL) in the python console, leave it for several hours and then try to download this URL). Both problems are solved after recreating 'pafy.new' instance. This issue may be considered as not-a-bug, but I leave it up to developers to decide whether to close it or not. The one thing that disturbs me is the following. This video is recent (published on 2018-08-21 13:00:04), so a mirror server (I suppose Youtube uses those) might not have received a full copy of the file, however, I was able to play the video in a browser the moment I have encountered this problem.

**Comment by ritiek** [comment] 2018-08-22 06:20
> The other one that I have encountered was "urllib.error.HTTPError: HTTP Error 403: Forbidden" when trying to download after a certain time-out (just do pafy.new(any_URL) in the python console, leave it for several hours and then try to download this URL)

This is probably because pafy fetches the actual YouTube stream URLs when `pafy.new` is called but these stream URLs are temporary and expire after some time (last for an hour or so? I don't know exactly). So, when you finally try to download them, these URLs are no longer valid and YouTube returns a 403 Forbidden.

I am talking about these kinds of URLs here: `https://r1---sn-ci5gup-pmjl.googlevideo.com/videoplayback?ei=YQB9W...`

We could add a check in pafy to test if the URL is valid otherwise fetch the new URL and return that but I am not sure whether this would be worth it since people usually do not wait for hours before finally doing something with the URL.

**Comment by sklprogs** [comment] 2018-08-22 06:38
@ritiek 

> We could add a check in pafy to test if the URL is valid otherwise fetch the new URL and return that but I am not sure whether this would be worth it since people usually do not wait for hours before finally doing something with the URL

Well, I don't think you should do anything with this, since it's better to keep the library as simple as possible. Since I use a GUI wrapper for your library, a user can actually encounter this problem, but I'll just add recreating pafy.new in the try-except condition. Thank you.

**Comment by ritiek** [comment] 2018-08-22 06:39
Yep, I think so too. I'll close this then.

**Closed as completed by ritiek** 2018-08-22 06:39 UTC
Labels: bug
