### ISSUE TITLE
RuntimeError: maximum recursion depth exceeded

### ISSUE THREAD

**Issue by dslackw** [mps-youtube/pafy#105] opened 2015-07-03 22:20 UTC
```
.
.
.
  File "/usr/bin/ytdl", line 68, in xprint
    xprint(xenc(stuff), end=end)
  File "/usr/bin/ytdl", line 68, in xprint
    xprint(xenc(stuff), end=end)
  File "/usr/bin/ytdl", line 68, in xprint
    xprint(xenc(stuff), end=end)
  File "/usr/bin/ytdl", line 68, in xprint
    xprint(xenc(stuff), end=end)
  File "/usr/bin/ytdl", line 68, in xprint
    xprint(xenc(stuff), end=end)
```
but work well with version 0.3.72

**Comment by ids1024** [comment] 2015-07-04 01:00
Duplicate of #101

**Closed** 2015-07-15 16:34 UTC
