### ISSUE TITLE
exception in Thread-1

### ISSUE THREAD

**Issue by matteomarchesi** [mps-youtube/pafy#144] opened 2016-05-26 10:03 UTC
Hello,
    I'm not able to run mps-youtube in Ubuntu Xenial while it worked fine in Thrusty.
When I try to listen to a music I'm getting this errors.
I've already re-installed Python3 but the issue is still there.
Any idea?

 Exception in thread Thread-1:
Traceback (most recent call last):
File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
self.run()
File "/usr/lib/python3.5/threading.py", line 862, in run
self._target(*self._args, **self._kwargs)
File "/home/matteo/.local/lib/python3.5/site-packages/mps_youtube/main.py", line 2475, in _preload
stream = streams.select(streams.get(song), audio=not video, m4a_ok=m4a)
File "/home/matteo/.local/lib/python3.5/site-packages/mps_youtube/streams.py", line 50, in get
p = get_pafy(vid, force=force, callback=callback)
File "/home/matteo/.local/lib/python3.5/site-packages/mps_youtube/util.py", line 175, in get_pafy
p = pafy.new(item.ytid, callback=callback_fn)
File "/home/matteo/.local/lib/python3.5/site-packages/pafy/pafy.py", line 125, in new
return Pafy(url, basic, gdata, signature, size, callback, ydl_opts)
File "/home/matteo/.local/lib/python3.5/site-packages/pafy/backend_internal.py", line 47, in __init__
super(InternPafy, self).__init__(*args, **kwargs)
File "/home/matteo/.local/lib/python3.5/site-packages/pafy/backend_shared.py", line 95, in __init__
self._fetch_basic()
File "/home/matteo/.local/lib/python3.5/site-packages/pafy/backend_internal.py", line 94, in _fetch_basic
self.callback)
File "/home/matteo/.local/lib/python3.5/site-packages/pafy/backend_internal.py", line 433, in get_js_sm
dash_url = stream_info['dashmpd']
KeyError: 'dashmpd'

Traceback (most recent call last):
File "/usr/local/bin/mpsyt", line 9, in <module>
load_entry_point('mps-youtube==0.2.6', 'console_scripts', 'mpsyt')()
File "/home/matteo/.local/lib/python3.5/site-packages/mps_youtube/main.py", line 3695, in main
if matchfunction(i.function, i.regex, userinput):
File "/home/matteo/.local/lib/python3.5/site-packages/mps_youtube/main.py", line 3644, in matchfunction
func(*matches)
File "/home/matteo/.local/lib/python3.5/site-packages/mps_youtube/main.py", line 2427, in play
play_range(songlist, shuffle, repeat, override)
File "/home/matteo/.local/lib/python3.5/site-packages/mps_youtube/main.py", line 2519, in play_range
returncode = playsong(song, override=override)
File "/home/matteo/.local/lib/python3.5/site-packages/mps_youtube/main.py", line 1138, in playsong
streams.get(song, force=failcount, callback=screen.writestatus)
File "/home/matteo/.local/lib/python3.5/site-packages/mps_youtube/streams.py", line 50, in get
p = get_pafy(vid, force=force, callback=callback)
File "/home/matteo/.local/lib/python3.5/site-packages/mps_youtube/util.py", line 175, in get_pafy
p = pafy.new(item.ytid, callback=callback_fn)
File "/home/matteo/.local/lib/python3.5/site-packages/pafy/pafy.py", line 125, in new
return Pafy(url, basic, gdata, signature, size, callback, ydl_opts)
File "/home/matteo/.local/lib/python3.5/site-packages/pafy/backend_internal.py", line 47, in __init__
super(InternPafy, self).__init__(*args, **kwargs)
File "/home/matteo/.local/lib/python3.5/site-packages/pafy/backend_shared.py", line 95, in __init__
self._fetch_basic()
File "/home/matteo/.local/lib/python3.5/site-packages/pafy/backend_internal.py", line 94, in _fetch_basic
self.callback)
File "/home/matteo/.local/lib/python3.5/site-packages/pafy/backend_internal.py", line 433, in get_js_sm
dash_url = stream_info['dashmpd']
KeyError: 'dashmpd'

**Comment by ids1024** [comment] 2016-05-26 22:20
Duplicate of #140.

**Closed by ids1024** 2016-05-26 22:20 UTC
